# Generated by Django 6.0.3 on 2026-05-01 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考试标题')),
                ('description', models.TextField(blank=True, verbose_name='考试描述')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='考试时长（分钟）')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='满分')),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='及格百分比，例如 60 表示 60%', verbose_name='及格线')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='题号')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('true_false', '判断题')], default='single_choice', max_length=20, verbose_name='题目类型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('option_a', models.CharField(blank=True, max_length=500, verbose_name='选项 A')),
                ('option_b', models.CharField(blank=True, max_length=500, verbose_name='选项 B')),
                ('option_c', models.CharField(blank=True, max_length=500, verbose_name='选项 C')),
                ('option_d', models.CharField(blank=True, max_length=500, verbose_name='选项 D')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('score', models.PositiveIntegerField(default=5, verbose_name='分值')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='所属考试')),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
                'ordering': ['question_number'],
                'unique_together': {('exam', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='UserExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总题数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='答对题数')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否及格')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='考试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户考试记录',
                'verbose_name_plural': '用户考试记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=10, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='试题')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.userexamattempt', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '用户答案',
                'verbose_name_plural': '用户答案',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
