# Generated by Django 5.2.11 on 2026-02-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code_challenge_prompt',
            field=models.TextField(blank=True, help_text='Initial code or prompt for the code challenge.'),
        ),
    ]
