# Generated by Django 5.2.11 on 2026-02-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_code_challenge_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='score',
            field=models.IntegerField(default=0, help_text='Quiz score for this lesson'),
        ),
    ]
