# Generated by Django 5.2.11 on 2026-02-21 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_userlessonprogress_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': '小节', 'verbose_name_plural': '小节'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': '测验', 'verbose_name_plural': '测验'},
        ),
        migrations.AlterModelOptions(
            name='usercourseprogress',
            options={'verbose_name': '用户课程进度', 'verbose_name_plural': '用户课程进度'},
        ),
        migrations.AlterModelOptions(
            name='userlessonprogress',
            options={'verbose_name': '用户小节进度', 'verbose_name_plural': '用户小节进度'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=200, verbose_name='章节标题'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='课程标题'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter', verbose_name='所属章节'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='code_challenge_prompt',
            field=models.TextField(blank=True, help_text='代码挑战的初始代码或提示', verbose_name='代码挑战提示'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='课程内容的 Markdown 文本', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', '图文课程'), ('quiz', '测验'), ('code', '代码挑战')], default='text', max_length=10, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='小节标题'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, help_text='正确答案的解析', verbose_name='解析'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson', verbose_name='所属小节'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_a',
            field=models.CharField(max_length=200, verbose_name='选项 A'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_b',
            field=models.CharField(max_length=200, verbose_name='选项 B'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_c',
            field=models.CharField(max_length=200, verbose_name='选项 C'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_d',
            field=models.CharField(max_length=200, verbose_name='选项 D'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='current_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson', verbose_name='当前学习小节'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='小节'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='score',
            field=models.IntegerField(default=0, help_text='本节测验得分', verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
