create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  is_approved boolean not null default true,
  xp integer not null default 0,
  level integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  "order" integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  "order" integer not null default 0
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  title text not null,
  content text,
  code_challenge_prompt text,
  lesson_type text not null default 'text',
  "order" integer not null default 0
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null,
  explanation text
);

create table if not exists public.user_course_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  is_completed boolean not null default false,
  completed_at timestamptz,
  current_lesson_id bigint references public.lessons(id) on delete set null,
  unique(user_id, course_id)
);

create table if not exists public.user_lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  is_completed boolean not null default false,
  score integer not null default 0,
  completed_at timestamptz,
  unique(user_id, lesson_id)
);

create table if not exists public.exams (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  subject text,
  set_name text,
  duration_minutes integer not null default 60,
  total_score integer not null default 100,
  markdown_content text not null,
  parsed_json jsonb,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.exam_attempts (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid not null references public.exams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null,
  total_questions integer not null,
  correct_count integer not null,
  answers jsonb not null default '{}'::jsonb,
  submitted_at timestamptz not null default now()
);

create or replace function public.parse_exam_markdown(input_md text)
returns jsonb
language plpgsql
as $$
declare
  line text;
  lines text[];
  title text := '未命名试卷';
  duration_minutes integer := 60;
  total_score integer := 100;
  questions jsonb := '[]'::jsonb;
  current_number text := null;
  current_question text := '';
  current_a text := '';
  current_b text := '';
  current_c text := '';
  current_d text := '';
  current_answer text := null;
  current_explanation text := '';
begin
  lines := string_to_array(coalesce(input_md, ''), E'\n');

  foreach line in array lines loop
    if line like '# %' then
      title := trim(both from regexp_replace(line, '^#\s*', ''));
    elsif line ~ '^考试时间：' then
      duration_minutes := coalesce(nullif(regexp_replace(line, '[^0-9]', '', 'g'), '')::integer, duration_minutes);
    elsif line ~ '^满分：' then
      total_score := coalesce(nullif(regexp_replace(line, '[^0-9]', '', 'g'), '')::integer, total_score);
    elsif line ~ '^###\s+' then
      if current_number is not null then
        questions := questions || jsonb_build_object(
          'number', current_number,
          'question', current_question,
          'options', jsonb_build_array(
            jsonb_build_object('key', 'A', 'text', current_a),
            jsonb_build_object('key', 'B', 'text', current_b),
            jsonb_build_object('key', 'C', 'text', current_c),
            jsonb_build_object('key', 'D', 'text', current_d)
          ),
          'answer', current_answer,
          'explanation', current_explanation
        );
      end if;

      current_number := trim(both from regexp_replace(line, '^###\s*', ''));
      current_question := '';
      current_a := '';
      current_b := '';
      current_c := '';
      current_d := '';
      current_answer := null;
      current_explanation := '';
    elsif line ~ '^题目：' then
      current_question := trim(both from regexp_replace(line, '^题目：\s*', ''));
    elsif line ~ '^A\.' then
      current_a := trim(both from regexp_replace(line, '^A\.\s*', ''));
    elsif line ~ '^B\.' then
      current_b := trim(both from regexp_replace(line, '^B\.\s*', ''));
    elsif line ~ '^C\.' then
      current_c := trim(both from regexp_replace(line, '^C\.\s*', ''));
    elsif line ~ '^D\.' then
      current_d := trim(both from regexp_replace(line, '^D\.\s*', ''));
    elsif line ~ '^答案：' then
      current_answer := upper(trim(both from regexp_replace(line, '^答案：\s*', '')));
    elsif line ~ '^解析：' then
      current_explanation := trim(both from regexp_replace(line, '^解析：\s*', ''));
    end if;
  end loop;

  if current_number is not null then
    questions := questions || jsonb_build_object(
      'number', current_number,
      'question', current_question,
      'options', jsonb_build_array(
        jsonb_build_object('key', 'A', 'text', current_a),
        jsonb_build_object('key', 'B', 'text', current_b),
        jsonb_build_object('key', 'C', 'text', current_c),
        jsonb_build_object('key', 'D', 'text', current_d)
      ),
      'answer', current_answer,
      'explanation', current_explanation
    );
  end if;

  return jsonb_build_object(
    'title', title,
    'duration_minutes', duration_minutes,
    'total_score', total_score,
    'questions', questions
  );
end;
$$;

create or replace function public.set_parsed_exam_json()
returns trigger
language plpgsql
as $$
begin
  new.parsed_json := public.parse_exam_markdown(new.markdown_content);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_parse_exam_markdown on public.exams;
create trigger trg_parse_exam_markdown
before insert or update of markdown_content on public.exams
for each row execute function public.set_parsed_exam_json();

create index if not exists idx_chapters_course_order on public.chapters(course_id, "order");
create index if not exists idx_lessons_chapter_order on public.lessons(chapter_id, "order");
create index if not exists idx_quizzes_lesson on public.quizzes(lesson_id);
create index if not exists idx_user_course_progress_user on public.user_course_progress(user_id);
create index if not exists idx_user_lesson_progress_user on public.user_lesson_progress(user_id);
create index if not exists idx_exam_attempts_user_exam on public.exam_attempts(user_id, exam_id);

alter table public.profiles enable row level security;
alter table public.user_course_progress enable row level security;
alter table public.user_lesson_progress enable row level security;
alter table public.exam_attempts enable row level security;
alter table public.exams enable row level security;
alter table public.courses enable row level security;
alter table public.chapters enable row level security;
alter table public.lessons enable row level security;
alter table public.quizzes enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = id);

drop policy if exists "profiles_login_lookup" on public.profiles;
create policy "profiles_login_lookup" on public.profiles
for select to anon using (true);

drop policy if exists "courses_public_read" on public.courses;
create policy "courses_public_read" on public.courses
for select using (true);

drop policy if exists "chapters_public_read" on public.chapters;
create policy "chapters_public_read" on public.chapters
for select using (true);

drop policy if exists "lessons_public_read" on public.lessons;
create policy "lessons_public_read" on public.lessons
for select using (true);

drop policy if exists "quizzes_public_read" on public.quizzes;
create policy "quizzes_public_read" on public.quizzes
for select using (true);

drop policy if exists "exams_public_read" on public.exams;
create policy "exams_public_read" on public.exams
for select using (published = true);

drop policy if exists "user_course_progress_own_all" on public.user_course_progress;
create policy "user_course_progress_own_all" on public.user_course_progress
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "user_lesson_progress_own_all" on public.user_lesson_progress;
create policy "user_lesson_progress_own_all" on public.user_lesson_progress
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "exam_attempts_own_all" on public.exam_attempts;
create policy "exam_attempts_own_all" on public.exam_attempts
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
